version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    image: python_${PYTHON_VERSION}
    ports:
      - "5000:5000"

  prometheus:
    image: ${PROMETEHUS_VERSION}
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: ${GRAFANA_VERSION}
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    # volumes:
    #   - grafana_data:/var/lib/grafana
    volumes:
     - 'grafana_storage:/var/lib/grafana'
    depends_on:
      - prometheus
volumes:
  grafana_storage: {}
